- name: play and task level variables
  hosts: local
  connection: local 
  vars:
    course: "devops"
    trainer: "siva"
  tasks:
    - name: print the variables
      vars:
        course: 'AWS'
        trainer: "praveen"
      ansible.builtin.debug:
        msg: "course is {{course}} and trainer is {{trainer}}"


# ansible-playbook -i inventory.ini 03_pb.yaml -> to run this playbook

# targetting same server, hence hosts:local and no need to give username and password as we gave connection: local as below:
# hosts: local
# connection: local 


# task level variables always override play level variables


# O/P:
# PLAY [play and task level variables] *****************************************************************

# TASK [Gathering Facts] **********************************************************************
# ok: [localhost]

# TASK [print the variables] ******************************************************************
# ok: [localhost] => {
#     "msg": "course is AWS and trainer is praveen"
# }

# PLAY RECAP **********************************************************************************
# localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


