- name: play level variables
  hosts: local
  connection: local 
  vars:
    course: "devops"
    trainer: "siva"
  tasks:
    - name: print the variables
      vars:
        course: 'AWS'
        trainer: "praveen"
      ansible.builtin.debug:
        msg: "course is {{course}} and trainer is {{trainer}}"





# hosts: local
# connection: local 
# targetting same server and no need to give username and password as we gave connection: local 


# PLAY [play level variables] *****************************************************************

# TASK [Gathering Facts] **********************************************************************
# ok: [localhost]

# TASK [print the variables] ******************************************************************
# ok: [localhost] => {
#     "msg": "course is devops and trainer is siva"
# }

# PLAY RECAP **********************************************************************************
# localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

