- name: print username and password
  hosts: local
  connection: local
  tasks:
    - name: print variable from inventory
      ansible.builtin.debug:
        msg: "course is {{course}}"


  # Hence Variables Order is  Task > Inventory > Play > vars_files