- name: variables from arg
  hosts: local
  connection: local
  tasks:
    - name: print variable from cmd line
      ansible.builtin.debug:
        msg: "name is {{name}}"


# ansible-playbook -i inventory.ini -e 'name="VARUN APPALLA"' 07_pb.yaml

# Hence Variables Order is  cmd line Args > Task > vars_files > Prompt > Play > Inventory 