- name: Conditions
  hosts: local
  connection: local
  vars:
    sessions_count: 6
  tasks:
    - name: check sessions count greater than 1
      ansible.builtin.debug:
        msg: "Yes it is greater than 1"
      when: sessions_count>1
       