- name: loops
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package:
        name: {{item.name}}
        state: present
      loop:
        - {name: "mysql", state: "absent"}
        - {name: "nginx", state: "absent"}
        - {name: "zip", state: "absent"}


   
      