- name: filters/functions
  hosts: local
  connection: local
  become: yes
  vars:
    topics: linux,shell,docker,terraform
  tasks:
    - name: default msg
      ansible.builtin.debug:
        msg: "Hi QA {{greeting | default('GD MRG') }}"

    - name: comvert string to list
      ansible.builtin.debug:
        msg: "{{ topics | split(',') }}"