- name: Loops
  hosts: localhost
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package: 
        name: "{{item}}" # item is default keyword
        state: present
      loop:
        - git
        - mysql
        - postfix