- name: Loops
  hosts: localhost
  become: yes
  tasks:
    - name: install/uninstall packages
      ansible.builtin.package: 
        name: "{{item.name}}" # item is default keyword
        state: "{{item.state}}"
      loop:
        - {name:'git', state:'present'}
        - {name:'sql', state:'absent'}
        - {name:'postfix', state:'absent'}
        - {name:'nginx', state:'present'}
