# play level variables
- name: variables from PLAY level
  hosts: localhost
  vars_files:
    - variables.yaml
  vars_prompt:
    - name: Person
      prompt: Please enter your name
      private: false 

    - name: Wishes
      prompt: Please enter your wishes
      private: false 

  vars: 
    Person: "QA from play"
    Wishes: "Morning from play"
  tasks:
    - name: check variables
      vars:  
        Person: "Siva from task"
        Wishes: "Morning from task"

      ansible.builtin.debug:
        msg: "Hi, {{Person}}, Good {{Wishes}}"


# ansible-playbook -i inventory -e ansible_user=centos -e ansible_password=DevOps321 vars_preference_10.yaml -e "Person=QAfromcmd" -e "Wishes=morningfromcmd"
# first pref is always from cmd, second pref is task level, third pref is file level,fourth pref is prompt level,
# fifth pref is play level, sixth pref is inventory level